version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: aurora_container
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aurora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Если есть файл инициализации, можно добавить:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql\

  redis:
      image: redis:7.0
      container_name: redis_cache
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - redis_data:/data
      command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  postgres_data:
  redis_data: