# Generated by Django 4.2.17 on 2025-01-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
