# Generated by Django 4.2.17 on 2025-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('can_add', 'Доступ добавить'), ('can_update', 'Доступ обновить'), ('can_delete', 'Доступ удалить'), ('can_view', 'Доступ на чтение')], default='can_view', max_length=100)),
                ('resource', models.CharField(choices=[('restaurant', 'restaurant'), ('order', 'order'), ('category', 'category'), ('menu', 'menu'), ('user', 'user')], default='menu', max_length=255)),
                ('perms', models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
