# Generated by Django 4.2.17 on 2025-01-12 12:22

import core.utils.directory_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=225)),
                ('adress', models.CharField(max_length=225)),
                ('telegram_link', models.CharField(max_length=225)),
                ('instagram_link', models.CharField(max_length=225)),
                ('orders', models.BooleanField(default=False)),
                ('waiter', models.BooleanField(default=False)),
                ('backgroud_photo', models.ImageField(upload_to=core.utils.directory_path.upload_path_vendor_backgroud)),
                ('logo', models.ImageField(upload_to=core.utils.directory_path.upload_path_vendor_logo)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
