# Generated by Django 4.2.17 on 2025-02-04 00:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='user',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact_entity',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Введённый номер телефона неправильно. Пример +998(XX)XXX-XX-XX', regex='^(\\+998)(\\d{9})$')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact_support',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Введённый номер телефона неправильно. Пример +998(XX)XXX-XX-XX', regex='^(\\+998)(\\d{9})$')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='legal_adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='orders_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stir',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waiter_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
