# Generated by Django 4.2.17 on 2025-02-04 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_rename_user_restaurant_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
