# Generated by Django 4.2.17 on 2025-02-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelTable(
            name='category',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='product_menu',
        ),
    ]
