# Generated by Django 4.2.17 on 2025-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_menu_options_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='currency',
            field=models.CharField(choices=[("so'm", "UZS (so'm)"), ('$', 'Доллар ($)'), ('€', 'Евро (€)'), ('₸', 'Тенге (₸)'), ('₼', 'Манат (₼)'), ('₾', 'Лари (₾)'), ('֏', 'Драм (֏)'), ('₽', 'Рубль (₽)'), ('⊆', 'Сом (⊆)'), ('₺', 'Лира (₺)')], default="so'm", max_length=100),
        ),
    ]
